
# log settings for the application (RUST_LOG format). Default below
# 
# log = "poc_ingest=debug,poc_store=info"

# Mode to run the ingest in. This adjustst the allowed grpc endpoints. "lora" or
# "mobile". Required
mode = "lora"

# Token for ingest grpc endpoint bearer authentication. This is required for
# "mobile" mode and ignored for lora. 
#
# token = "api-token"

# Listen addres for public grpc. Default below
#
# listen = "0.0.0.0:9081"

[cache]
# Local cache for ingested data 

# Cache folder to use. Default blow
#
# cache = "/var/data/ingest"

[output]
# Output bucket for ingested data

# Name of bucket to write details to. Required
#
bucket = "ingest-bucket"

# Region for bucket. Defaults to below
#
# region = "us-west-2"

# Optional URL for AWS api endpoint. Inferred from aws config settings or aws
# IAM context by default
#
# endpoint = "https://aws-s3-bucket.aws.com"

[metrics]

# Endpoint for metrics. Default below
#
# endpoint = "127.0.0.1:19000"