[package]
name = "poc-iot-verifier"
version = "0.1.0"
description = "PoC Verifier Server for the Helium Lora Network"
edition.workspace = true
authors.workspace = true
license.workspace = true

[build-dependencies]
cmake = "0.1"

[dependencies]
dotenv = {workspace = true}
clap = {workspace = true}
thiserror = {workspace = true}
serde =  {workspace = true}
serde_json = {workspace = true}
sqlx = {workspace = true}
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
base64 = {workspace = true}
sha2 = {workspace = true}
http = {workspace = true}
tonic = {workspace = true}
triggered = {workspace = true}
futures = {workspace = true}
futures-util = {workspace = true}
prost = {workspace = true}
chrono = { workspace = true }
helium-proto = { workspace = true }
helium-crypto = {workspace = true }
file-store = { path = "../file_store" }
denylist = {path = "../denylist"}
async-trait = "*"
h3ron = "*"
geo-types = "*"
geo = "*"
xorf = "*"
lazy_static = {workspace = true}
once_cell = {workspace = true}

