[package]
name = "poc-store"
version = "0.1.0"
edition = "2021"
description = "Ingest Store Library"
authors = ["Marc Nijdam <marc@nova-labe.com>"]
license = "Apache-2.0"

[dependencies]
clap = {version = "3", features = ["derive"]}
serde = "1"
serde_json = "1"
thiserror = "1"
tokio = { version = "1", default-features=false, features=["fs"] }
tokio-util = "0"
async-compression = {version = "0", features = ["tokio", "gzip"]}
futures = "*"
futures-core = "*"
futures-util = "*"
prost = "0"
bytes = "*"
regex = "1"
lazy_static = "1"
chrono = {version = "0", features = ["serde"]}
helium-proto = {git = "https://github.com/helium/proto", branch = "master", features = ["services"]}
csv = "*"
base64 = "0"
bs58 = "0.4"
base64-url = "1.4.13"
helium-crypto = {git = "https://github.com/helium/helium-crypto-rs", tag="v0.3.3", features = ["multisig"]}
