[package]
name = "poc5g-status"
version = "0.1.0"
edition = "2021"
description = "Status Server for the Helium Mobile Network"
authors = ["Marc Nijdam <marc@nova-labs.com>"]
license = "Apache-2.0"


[dependencies]
dotenv = "0"
thiserror = "1"
serde =  {version = "1", features=["derive"]}
serde_json = "1"
clap = {version = "3", features = ["derive"]}
sqlx = {version = "0", features = ["postgres", "uuid", "decimal", "chrono", "migrate", "macros", "runtime-tokio-rustls"]}
tokio = { version = "1", default-features=false, features=["fs", "macros", "signal", "rt", "process", "time"] }
tracing = "0"
tracing-subscriber = { version = "0", features = ["env-filter"] }
axum = "0"
tower-http = {version = "*", features = ["auth", "trace"]}
base64 = "0"
sha2 = "*"
lazy_static = "*"
chrono = {version = "0", features = ["serde"]}
triggered = "0"
futures = "*"
futures-util = "*"
prost = "*"
hyper = "*"
once_cell = "1"
file-store = {path = "../file_store"}
poc-metrics = { path = "../metrics" }
helium-proto = {git = "https://github.com/helium/proto", branch = "master", features = ["services"]}
helium-crypto = {git = "https://github.com/helium/helium-crypto-rs", tag="v0.4.4", features=["sqlx-postgres"]}
rust_decimal = "1"
rust_decimal_macros = "1"
tonic = "0"
http = "*"
metrics = "0"
strum = "*"

[package.metadata.deb]
depends = "$auto"
assets = [
    ["target/release/poc5g-status", "/opt/poc5g-status/bin/", "755"],
    ["pkg/deb/env-template", "/usr/share/poc5g-status/env-template", "644"]
]
maintainer-scripts = "deb/pkg/"
systemd-units = { }
