[package]
name = "poc-iot-injector"
version = "0.1.0"
description = "PoC IOT injector Server for the Helium Network"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
rand = "*"
rust_decimal = {workspace = true}
config = {workspace = true}
clap = {workspace = true}
thiserror = {workspace = true}
serde =  {workspace = true}
serde_json = {workspace = true}
http-serde = {workspace = true}
futures = {workspace = true}
futures-util = {workspace = true}
prost = {workspace = true}
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = {workspace = true}
sqlx = {workspace = true}
tonic = {workspace = true}
tokio = {workspace = true}
triggered = {workspace = true}
base64 = {workspace = true}
sha2 = {workspace = true}
rust_decimal_macros = {workspace = true}
metrics = {workspace = true }
metrics-exporter-prometheus = { workspace = true }
helium-crypto = { workspace = true }
helium-proto = { workspace = true }
poc-metrics = { path = "../metrics" }
file-store = {path = "../file_store"}
db-store = {path = "../db_store"}
node-follower = {path = "../node_follower"}
density-scaler = {path = "../density_scaler"}

[package.metadata.deb]
depends = "$auto"
assets = [
  [
    "target/release/poc-iot-injector",
    "/opt/poc-iot-injector/bin/",
    "755",
  ],
  [
    "pkg/deb/env-template",
    "/usr/share/poc-iot-injector/env-template",
    "644",
  ],
]
maintainer-scripts = "pkg/deb/"
systemd-units = {}
